export const cards = [
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
        link: 'https://github.com/BryamSENAC',
    },
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
        link: 'https://github.com/BryamSENAC',
    },
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
        link: 'https://github.com/BryamSENAC',
    },
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
        link: 'https://github.com/BryamSENAC',
    },
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
        link: 'https://github.com/BryamSENAC',
    },
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
        link: 'https://github.com/BryamSENAC',
    },
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
        link: 'https://github.com/BryamSENAC',
    },
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
        link: 'https://github.com/BryamSENAC',
    },
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
        link: 'https://github.com/BryamSENAC',
    },
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
        link: 'https://github.com/BryamSENAC',
    },
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
        link: 'https://github.com/BryamSENAC',
    },
    {
        title: 'Nome Projeto',
        lp: 'Linguagens',
        description: 'Descrição do projeto bem breve falando a linguagem usada e para que serve',
        img: 'https://cdn-icons-png.flaticon.com/512/1063/1063365.png',
    }
]