export const projects = [
    {
        project: 'Nome do Projeto',
        img: 'https://cdn-icons-png.flaticon.com/512/16/16410.png',
        languages: 'LINGUAGENS',
        description: 'Descrição do projeto, nada muito longo se não estraga o design',
        link: 'https://github.com/bryamSENAC',
    },
    {
        project: 'Nome do Projeto',
        img: 'https://cdn-icons-png.flaticon.com/512/16/16410.png',
        languages: 'LINGUAGENS',
        description: 'Descrição do projeto, nada muito longo se não estraga o design',
        link: 'https://github.com/bryamSENAC',
    },
    {
        project: 'Nome do Projeto',
        img: 'https://cdn-icons-png.flaticon.com/512/16/16410.png',
        languages: 'LINGUAGENS',
        description: 'Descrição do projeto, nada muito longo se não estraga o design',
        link: 'https://github.com/bryamSENAC',
    },
    {
        project: 'Nome do Projeto',
        img: 'https://cdn-icons-png.flaticon.com/512/16/16410.png',
        languages: 'LINGUAGENS',
        description: 'Descrição do projeto, nada muito longo se não estraga o design',
        link: 'https://github.com/bryamSENAC',
    },
    {
        project: 'Nome do Projeto',
        img: 'https://cdn-icons-png.flaticon.com/512/16/16410.png',
        languages: 'LINGUAGENS',
        description: 'Descrição do projeto, nada muito longo se não estraga o design',
        link: 'https://github.com/bryamSENAC',
    },
    {
        project: 'Nome do Projeto',
        img: 'https://cdn-icons-png.flaticon.com/512/16/16410.png',
        languages: 'LINGUAGENS',
        description: 'Descrição do projeto, nada muito longo se não estraga o design',
        link: 'https://github.com/bryamSENAC',
    },
    {
        project: 'Nome do Projeto',
        img: 'https://cdn-icons-png.flaticon.com/512/16/16410.png',
        languages: 'LINGUAGENS',
        description: 'Descrição do projeto, nada muito longo se não estraga o design',
        link: 'https://github.com/bryamSENAC',
    },
    {
        project: 'Nome do Projeto',
        img: 'https://cdn-icons-png.flaticon.com/512/16/16410.png',
        languages: 'LINGUAGENS',
        description: 'Descrição do projeto, nada muito longo se não estraga o design',
        link: 'https://github.com/bryamSENAC',
    },
    {
        project: 'Nome do Projeto',
        img: 'https://cdn-icons-png.flaticon.com/512/16/16410.png',
        languages: 'LINGUAGENS',
        description: 'Descrição do projeto, nada muito longo se não estraga o design',
        link: 'https://github.com/bryamSENAC',
    },
    {
        project: 'Nome do Projeto',
        img: 'https://cdn-icons-png.flaticon.com/512/16/16410.png',
        languages: 'LINGUAGENS',
        description: 'Descrição do projeto, nada muito longo se não estraga o design',
        link: 'https://github.com/bryamSENAC',
    },
    
]